"use client";
import { useEffect, useRef, useState } from "react";
import * as pdfjs from "pdfjs-dist";
import type { PDFDocumentProxy } from "pdfjs-dist";
import { DEFAULT_PRINT_SETTINGS, getDraftSettingsStorageKey, getPrintablePageCount, type FilePrintSettings } from "@/lib/print-settings";
pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.min.mjs", import.meta.url).toString();
const THUMBNAIL_SCALE=0.28, PREVIEW_SCALE=1.5;
async function draw(pdf:PDFDocumentProxy,n:number,canvas:HTMLCanvasElement,scale:number){const page=await pdf.getPage(n);const view=page.getViewport({scale});const ctx=canvas.getContext("2d",{alpha:false});if(!ctx)throw new Error("Браузер не поддерживает предпросмотр PDF.");canvas.width=Math.ceil(view.width);canvas.height=Math.ceil(view.height);await page.render({canvas,canvasContext:ctx,viewport:view}).promise;}
function Thumb({pdf,n,selected,included,onClick}:{pdf:PDFDocumentProxy;n:number;selected:boolean;included:boolean;onClick:()=>void}){const canvas=useRef<HTMLCanvasElement>(null);useEffect(()=>{if(canvas.current)void draw(pdf,n,canvas.current,THUMBNAIL_SCALE).catch(()=>undefined)},[pdf,n]);return <button type="button" onClick={onClick} aria-pressed={selected} className={`rounded-xl border p-2 text-left ${selected?"border-blue-700 bg-blue-50":"border-slate-200 bg-white"} ${included?"":"opacity-50"}`}><div className="relative overflow-hidden rounded-lg bg-slate-100"><canvas ref={canvas} className="block h-auto w-full" />{!included&&<span className="absolute inset-0 flex items-center justify-center bg-slate-900/30 text-xs font-bold text-white">Не печатать</span>}</div><span className={`mt-2 block text-center text-xs font-bold ${included?"":"text-red-700 line-through"}`}>Страница {n}</span></button>}
export function PrintDraftViewer({draftId}:{draftId:string}){const [pdf,setPdf]=useState<PDFDocumentProxy|null>(null),[error,setError]=useState(""),[selectedPage,setSelectedPage]=useState(1),[selected,setSelected]=useState<Set<number>>(new Set()),[settings,setSettings]=useState<FilePrintSettings>({...DEFAULT_PRINT_SETTINGS,defaults:{...DEFAULT_PRINT_SETTINGS.defaults},pageOverrides:{}});const preview=useRef<HTMLCanvasElement>(null);
useEffect(()=>{try{const saved=localStorage.getItem(getDraftSettingsStorageKey(draftId));if(saved)setSettings(JSON.parse(saved))}catch{}let disposed=false;let document:PDFDocumentProxy|null=null;void (async()=>{try{const response=await fetch(`/api/print-drafts/${draftId}/preview`,{cache:"no-store"});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.error??"Не удалось открыть документ.");document=await pdfjs.getDocument({data:await response.arrayBuffer()}).promise;if(!disposed)setPdf(document)}catch(e){if(!disposed)setError(e instanceof Error?e.message:"Не удалось открыть документ.")}})();return()=>{disposed=true;if(document)void document.destroy()}},[draftId]);
useEffect(()=>{localStorage.setItem(getDraftSettingsStorageKey(draftId),JSON.stringify(settings))},[draftId,settings]);
useEffect(()=>{if(pdf&&preview.current)void draw(pdf,selectedPage,preview.current,PREVIEW_SCALE).catch(()=>setError("Не удалось показать страницу."))},[pdf,selectedPage]);
if(error)return <main className="min-h-screen bg-slate-50 p-6"><p className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</p></main>;if(!pdf)return <main className="min-h-screen bg-slate-50 p-10 text-center font-bold">Подготавливаем предпросмотр…</main>;
const pages=Array.from({length:pdf.numPages},(_,i)=>i+1);const included=(n:number)=>settings.pageOverrides[n]?.included!==false;const update=(targets:number[],value:boolean)=>setSettings(old=>{const pageOverrides={...old.pageOverrides};for(const n of targets){if(value)delete pageOverrides[n];else pageOverrides[n]={pageNumber:n,included:false}}return {...old,pageOverrides}});return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-5 py-4"><div><p className="font-black">Предпросмотр печати</p><p className="text-sm text-slate-500">Печатать: {getPrintablePageCount(pdf.numPages,settings)} из {pdf.numPages} стр.</p></div><button type="button" onClick={()=>window.close()} className="rounded-xl border px-4 py-2 text-sm font-bold">Закрыть предпросмотр</button></div></header><div className="mx-auto grid max-w-7xl gap-6 p-5 lg:grid-cols-[1fr_360px]"><section><div className="mb-4 flex flex-wrap gap-2"><button type="button" onClick={()=>setSelected(new Set(pages))} className="rounded-lg border px-3 py-2 text-sm font-bold">Выбрать все</button><button type="button" onClick={()=>setSelected(new Set())} className="rounded-lg border px-3 py-2 text-sm font-bold">Снять выделение</button><button type="button" disabled={!selected.size} onClick={()=>update([...selected],false)} className="rounded-lg bg-red-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-50">Не печатать выбранные</button><button type="button" disabled={!selected.size} onClick={()=>update([...selected],true)} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-50">Вернуть выбранные</button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-4">{pages.map(n=><Thumb key={n} pdf={pdf} n={n} selected={selected.has(n)} included={included(n)} onClick={()=>{setSelected(x=>{const next=new Set(x);next.has(n)?next.delete(n):next.add(n);return next});setSelectedPage(n)}}/>)}</div></section><aside className="h-fit rounded-2xl bg-white p-4 shadow-sm"><p className="font-bold">Страница {selectedPage}</p><canvas ref={preview} className="mt-3 block h-auto max-w-full rounded bg-slate-100"/><button type="button" onClick={()=>update([selectedPage],!included(selectedPage))} className={`mt-4 w-full rounded-xl px-4 py-3 text-sm font-bold text-white ${included(selectedPage)?"bg-red-700":"bg-emerald-700"}`}>{included(selectedPage)?"Не печатать эту страницу":"Вернуть в печать"}</button></aside></div></main>}
